name: 'CI - Validate Infrastructure'
# Trigger On Pull request and Push request of any branch 

on:
  pull_request: 
    branches:
      - '*'
  push:
     branches:
      - '*'
  workflow_dispatch: #Allow manual trigger
env:
  TF_LOG: "INFO"
  TF_CLOUD_ORGANISATION: "DevOps-Pilot1"
  TF_WORKSPACE: "practice-ec2-terraform"

jobs:
  validate:
     name: 'validate terraform'
     runs-on: ubuntu-latest

     defaults:
      run:
       shell: bash
       working-directory: ./terraform

     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
         with: 
           terraform_version: 1.5.0
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

       #- name: Initialize Terraform
         #id: init
         #run: terraform fmt -check -recursive
         #continue-on-error: true
      
       #- name: Validate Terraform Configuration
        # id: validate
        # run: terraform validate

       - name: Initialize Terraform
         id: init
         run: terraform init
         
       - name: Validate Terraform Configuration
         id: validate
         run: terraform validate

       - name: Run TF Sec
         uses: aquasecurity/tfsec-action@v1.0.0
         continue-on-error: true

       - name: Run TFLint
         uses: terraform-linters/setup-tflint@v3
         continue-on-error: true
      
       - name: Post Validation Results
         if: always()
         run: |
           echo "Format Check: ${{ steps.fmt.outcome }}"
           echo "Validation: ${{ steps.validate.outcome }}"
